#git aliases
alias gs='git status '
alias ga='git add'
alias gad='git add -A'
alias gb='git branch '
alias gc='git commit'
alias gr='git rm'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias gp='git push'
